export interface PointData {
  id: string;
  name: string;
  lineId: string;
  order: number;
  region: string;
}

export const LINE_POINTS: Record<string, PointData[]> = {
  "010": [
    { id: "010-p1", name: "Terminal Santo Antônio", lineId: "010", order: 1, region: "Santo Antônio" },
    { id: "010-p2", name: "Igreja Matriz", lineId: "010", order: 2, region: "Centro" },
    { id: "010-p3", name: "Praça São Benedito", lineId: "010", order: 3, region: "Centro" },
    { id: "010-p4", name: "Hospital Roberto Silvares", lineId: "010", order: 4, region: "Centro" },
    { id: "010-p5", name: "CEPE", lineId: "010", order: 5, region: "CEPE" },
    { id: "010-p6", name: "Rodoviária", lineId: "010", order: 6, region: "Rodoviária" },
    { id: "010-p7", name: "Bairro Cohab I", lineId: "010", order: 7, region: "Cohab" },
    { id: "010-p8", name: "Bairro Cohab II", lineId: "010", order: 8, region: "Cohab" },
    { id: "010-p9", name: "Terminal Cohab", lineId: "010", order: 9, region: "Cohab" },
  ],
  "012": [
    { id: "012-p1", name: "Terminal Aroeira", lineId: "012", order: 1, region: "Aroeira" },
    { id: "012-p2", name: "Avenida Aroeira", lineId: "012", order: 2, region: "Aroeira" },
    { id: "012-p3", name: "Supermercado BH", lineId: "012", order: 3, region: "Aroeira" },
    { id: "012-p4", name: "Multivix", lineId: "012", order: 4, region: "Multivix" },
    { id: "012-p5", name: "CEPE", lineId: "012", order: 5, region: "CEPE" },
    { id: "012-p6", name: "Hospital Roberto Silvares", lineId: "012", order: 6, region: "Centro" },
    { id: "012-p7", name: "Ponto Final Roberto Silvares", lineId: "012", order: 7, region: "Roberto Silvares" },
  ],
  "013-aroeira-morada": [
    { id: "013am-p1", name: "Terminal Aroeira", lineId: "013-aroeira-morada", order: 1, region: "Aroeira" },
    { id: "013am-p2", name: "Avenida Aroeira", lineId: "013-aroeira-morada", order: 2, region: "Aroeira" },
    { id: "013am-p3", name: "IFES", lineId: "013-aroeira-morada", order: 3, region: "IFES" },
    { id: "013am-p4", name: "UFES", lineId: "013-aroeira-morada", order: 4, region: "UFES" },
    { id: "013am-p5", name: "Morada do Ribeirão", lineId: "013-aroeira-morada", order: 5, region: "Morada do Ribeirão" },
  ],
  "013-aroeira-cohab": [
    { id: "013ac-p1", name: "Terminal Aroeira", lineId: "013-aroeira-cohab", order: 1, region: "Aroeira" },
    { id: "013ac-p2", name: "Avenida Aroeira", lineId: "013-aroeira-cohab", order: 2, region: "Aroeira" },
    { id: "013ac-p3", name: "CEPE", lineId: "013-aroeira-cohab", order: 3, region: "CEPE" },
    { id: "013ac-p4", name: "Rodoviária", lineId: "013-aroeira-cohab", order: 4, region: "Rodoviária" },
    { id: "013ac-p5", name: "Cohab I", lineId: "013-aroeira-cohab", order: 5, region: "Cohab" },
    { id: "013ac-p6", name: "Cohab II", lineId: "013-aroeira-cohab", order: 6, region: "Cohab" },
  ],
  "021": [
    { id: "021-p1", name: "Terminal Santo Antônio", lineId: "021", order: 1, region: "Santo Antônio" },
    { id: "021-p2", name: "Igreja Matriz", lineId: "021", order: 2, region: "Centro" },
    { id: "021-p3", name: "Praça São Benedito", lineId: "021", order: 3, region: "Centro" },
    { id: "021-p4", name: "Hospital Roberto Silvares", lineId: "021", order: 4, region: "Centro" },
    { id: "021-p5", name: "CEPE", lineId: "021", order: 5, region: "CEPE" },
    { id: "021-p6", name: "Aviação", lineId: "021", order: 6, region: "Aviação" },
  ],
  "021-jacui": [
    { id: "021j-p1", name: "Terminal Santo Antônio", lineId: "021-jacui", order: 1, region: "Santo Antônio" },
    { id: "021j-p2", name: "Igreja Matriz", lineId: "021-jacui", order: 2, region: "Centro" },
    { id: "021j-p3", name: "Jacuí", lineId: "021-jacui", order: 3, region: "Jacuí" },
    { id: "021j-p4", name: "CEPE", lineId: "021-jacui", order: 4, region: "CEPE" },
    { id: "021j-p5", name: "Aviação", lineId: "021-jacui", order: 5, region: "Aviação" },
  ],
  "023": [
    { id: "023-p1", name: "Terminal Santo Antônio", lineId: "023", order: 1, region: "Santo Antônio" },
    { id: "023-p2", name: "Centro", lineId: "023", order: 2, region: "Centro" },
    { id: "023-p3", name: "Rodoviária", lineId: "023", order: 3, region: "Rodoviária" },
    { id: "023-p4", name: "Guriri", lineId: "023", order: 4, region: "Guriri" },
  ],
  "030": [
    { id: "030-p1", name: "Morada do Lago", lineId: "030", order: 1, region: "Morada do Lago" },
    { id: "030-p2", name: "Bairro Liberdade I", lineId: "030", order: 2, region: "Liberdade" },
    { id: "030-p3", name: "Bairro Liberdade II", lineId: "030", order: 3, region: "Liberdade" },
    { id: "030-p4", name: "Praça Liberdade", lineId: "030", order: 4, region: "Liberdade" },
  ],
  "040-porto": [
    { id: "040pt-p1", name: "Porto", lineId: "040-porto", order: 1, region: "Porto" },
    { id: "040pt-p2", name: "Centro", lineId: "040-porto", order: 2, region: "Centro" },
    { id: "040pt-p3", name: "CEPE", lineId: "040-porto", order: 3, region: "CEPE" },
    { id: "040pt-p4", name: "Rodoviária", lineId: "040-porto", order: 4, region: "Rodoviária" },
    { id: "040pt-p5", name: "Cohab I", lineId: "040-porto", order: 5, region: "Cohab" },
    { id: "040pt-p6", name: "Cohab II", lineId: "040-porto", order: 6, region: "Cohab" },
  ],
  "040-tereza": [
    { id: "040t-p1", name: "Santa Tereza", lineId: "040-tereza", order: 1, region: "Santa Tereza" },
    { id: "040t-p2", name: "Centro", lineId: "040-tereza", order: 2, region: "Centro" },
    { id: "040t-p3", name: "CEPE", lineId: "040-tereza", order: 3, region: "CEPE" },
    { id: "040t-p4", name: "Rodoviária", lineId: "040-tereza", order: 4, region: "Rodoviária" },
    { id: "040t-p5", name: "Cohab I", lineId: "040-tereza", order: 5, region: "Cohab" },
    { id: "040t-p6", name: "Cohab II", lineId: "040-tereza", order: 6, region: "Cohab" },
  ],
  "041": [
    { id: "041-p1", name: "Santa Tereza", lineId: "041", order: 1, region: "Santa Tereza" },
    { id: "041-p2", name: "Centro", lineId: "041", order: 2, region: "Centro" },
    { id: "041-p3", name: "Pedra D'Água", lineId: "041", order: 3, region: "Pedra D'Água" },
  ],
  "050-era": [
    { id: "050e-p1", name: "Nova Era", lineId: "050-era", order: 1, region: "Nova Era" },
    { id: "050e-p2", name: "CEPE", lineId: "050-era", order: 2, region: "CEPE" },
    { id: "050e-p3", name: "Centro", lineId: "050-era", order: 3, region: "Centro" },
    { id: "050e-p4", name: "Alvorada", lineId: "050-era", order: 4, region: "Alvorada" },
  ],
  "050-seac": [
    { id: "050s-p1", name: "Seac", lineId: "050-seac", order: 1, region: "Seac" },
    { id: "050s-p2", name: "CEPE", lineId: "050-seac", order: 2, region: "CEPE" },
    { id: "050s-p3", name: "Centro", lineId: "050-seac", order: 3, region: "Centro" },
    { id: "050s-p4", name: "Alvorada", lineId: "050-seac", order: 4, region: "Alvorada" },
  ],
  "051": [
    { id: "051-p1", name: "Centro", lineId: "051", order: 1, region: "Centro" },
    { id: "051-p2", name: "Praia do Bosque", lineId: "051", order: 2, region: "Bosque da Praia" },
  ],
  "051-seac": [
    { id: "051s-p1", name: "Seac", lineId: "051-seac", order: 1, region: "Seac" },
    { id: "051s-p2", name: "Centro", lineId: "051-seac", order: 2, region: "Centro" },
    { id: "051s-p3", name: "Praia do Bosque", lineId: "051-seac", order: 3, region: "Bosque da Praia" },
  ],
  "060": [
    { id: "060-p1", name: "Centro", lineId: "060", order: 1, region: "Centro" },
    { id: "060-p2", name: "Rodoviária", lineId: "060", order: 2, region: "Rodoviária" },
    { id: "060-p3", name: "Ideal", lineId: "060", order: 3, region: "Ideal" },
    { id: "060-p4", name: "Maternidade", lineId: "060", order: 4, region: "Maternidade" },
    { id: "060-p5", name: "Escola Master", lineId: "060", order: 5, region: "Escola Master" },
    { id: "060-p6", name: "Aviação", lineId: "060", order: 6, region: "Aviação" },
    { id: "060-p7", name: "Maria Amélia", lineId: "060", order: 7, region: "Maria Amélia" },
    { id: "060-p8", name: "Posto BR Mania", lineId: "060", order: 8, region: "Posto BR Mania" },
    { id: "060-p9", name: "BR-101", lineId: "060", order: 9, region: "BR-101" },
    { id: "060-p10", name: "Jambeiro", lineId: "060", order: 10, region: "Jambeiro" },
    { id: "060-p11", name: "Litorâneo", lineId: "060", order: 11, region: "Litorâneo" },
    { id: "060-p12", name: "IFES/UFES", lineId: "060", order: 12, region: "IFES" },
  ],
  "062": [
    { id: "062-p1", name: "Centro", lineId: "062", order: 1, region: "Centro" },
    { id: "062-p2", name: "IFES/UFES", lineId: "062", order: 2, region: "IFES" },
    { id: "062-p3", name: "Av. João XXIII", lineId: "062", order: 3, region: "Av. João XXIII" },
    { id: "062-p4", name: "BR-101", lineId: "062", order: 4, region: "BR-101" },
    { id: "062-p5", name: "Jambeiro", lineId: "062", order: 5, region: "Jambeiro" },
    { id: "062-p6", name: "US3", lineId: "062", order: 6, region: "US3" },
    { id: "062-p7", name: "Posto BR Mania", lineId: "062", order: 7, region: "Posto BR Mania" },
    { id: "062-p8", name: "Litorâneo", lineId: "062", order: 8, region: "Litorâneo" },
    { id: "062-p9", name: "Av. José Tozzi", lineId: "062", order: 9, region: "Av. José Tozzi" },
    { id: "062-p10", name: "Rodoviária", lineId: "062", order: 10, region: "Rodoviária" },
    { id: "062-p11", name: "Mercado Municipal", lineId: "062", order: 11, region: "Centro" },
    { id: "062-p12", name: "Maria Amélia", lineId: "062", order: 12, region: "Maria Amélia" },
  ],
  "064-villages-pedra": [
    { id: "064vp-p1", name: "Av. João XXIII", lineId: "064-villages-pedra", order: 1, region: "Av. João XXIII" },
    { id: "064vp-p2", name: "Av. José Tozzi", lineId: "064-villages-pedra", order: 2, region: "Av. José Tozzi" },
    { id: "064vp-p3", name: "Rodoviária", lineId: "064-villages-pedra", order: 3, region: "Rodoviária" },
    { id: "064vp-p4", name: "Centro", lineId: "064-villages-pedra", order: 4, region: "Centro" },
    { id: "064vp-p5", name: "Mercado Municipal", lineId: "064-villages-pedra", order: 5, region: "Centro" },
    { id: "064vp-p6", name: "Praça Amélia Boroto", lineId: "064-villages-pedra", order: 6, region: "Centro" },
    { id: "064vp-p7", name: "Roberto Silvares", lineId: "064-villages-pedra", order: 7, region: "Roberto Silvares" },
    { id: "064vp-p8", name: "Hospital Meridional", lineId: "064-villages-pedra", order: 8, region: "Hospital Meridional" },
    { id: "064vp-p9", name: "FVC", lineId: "064-villages-pedra", order: 9, region: "FVC" },
    { id: "064vp-p10", name: "CEPE", lineId: "064-villages-pedra", order: 10, region: "CEPE" },
    { id: "064vp-p11", name: "Multivix", lineId: "064-villages-pedra", order: 11, region: "Multivix" },
    { id: "064vp-p12", name: "San Remo", lineId: "064-villages-pedra", order: 12, region: "San Remo" },
    { id: "064vp-p13", name: "Maria Amélia", lineId: "064-villages-pedra", order: 13, region: "Maria Amélia" },
    { id: "064vp-p14", name: "Villages", lineId: "064-villages-pedra", order: 14, region: "Villages" },
    { id: "064vp-p15", name: "Litorâneo", lineId: "064-villages-pedra", order: 15, region: "Litorâneo" },
    { id: "064vp-p16", name: "IFES/UFES", lineId: "064-villages-pedra", order: 16, region: "IFES" },
    { id: "064vp-p17", name: "US3", lineId: "064-villages-pedra", order: 17, region: "US3" },
    { id: "064vp-p18", name: "Jambeiro", lineId: "064-villages-pedra", order: 18, region: "Jambeiro" },
  ],
  "064-villages-roberto": [
    { id: "064vr-p1", name: "Av. João XXIII", lineId: "064-villages-roberto", order: 1, region: "Av. João XXIII" },
    { id: "064vr-p2", name: "Av. José Tozzi", lineId: "064-villages-roberto", order: 2, region: "Av. José Tozzi" },
    { id: "064vr-p3", name: "Rodoviária", lineId: "064-villages-roberto", order: 3, region: "Rodoviária" },
    { id: "064vr-p4", name: "Centro", lineId: "064-villages-roberto", order: 4, region: "Centro" },
    { id: "064vr-p5", name: "Mercado Municipal", lineId: "064-villages-roberto", order: 5, region: "Centro" },
    { id: "064vr-p6", name: "Praça Amélia Boroto", lineId: "064-villages-roberto", order: 6, region: "Centro" },
    { id: "064vr-p7", name: "Roberto Silvares", lineId: "064-villages-roberto", order: 7, region: "Roberto Silvares" },
    { id: "064vr-p8", name: "Hospital Meridional", lineId: "064-villages-roberto", order: 8, region: "Hospital Meridional" },
    { id: "064vr-p9", name: "FVC", lineId: "064-villages-roberto", order: 9, region: "FVC" },
    { id: "064vr-p10", name: "CEPE", lineId: "064-villages-roberto", order: 10, region: "CEPE" },
    { id: "064vr-p11", name: "Multivix", lineId: "064-villages-roberto", order: 11, region: "Multivix" },
    { id: "064vr-p12", name: "San Remo", lineId: "064-villages-roberto", order: 12, region: "San Remo" },
    { id: "064vr-p13", name: "Maria Amélia", lineId: "064-villages-roberto", order: 13, region: "Maria Amélia" },
    { id: "064vr-p14", name: "Villages", lineId: "064-villages-roberto", order: 14, region: "Villages" },
    { id: "064vr-p15", name: "Litorâneo", lineId: "064-villages-roberto", order: 15, region: "Litorâneo" },
    { id: "064vr-p16", name: "IFES/UFES", lineId: "064-villages-roberto", order: 16, region: "IFES" },
    { id: "064vr-p17", name: "US3", lineId: "064-villages-roberto", order: 17, region: "US3" },
    { id: "064vr-p18", name: "Jambeiro", lineId: "064-villages-roberto", order: 18, region: "Jambeiro" },
  ],
  "068": [
    { id: "068-p1", name: "Centro", lineId: "068", order: 1, region: "Centro" },
    { id: "068-p2", name: "Mercado Municipal", lineId: "068", order: 2, region: "Centro" },
    { id: "068-p3", name: "Praça Amélia Boroto", lineId: "068", order: 3, region: "Centro" },
    { id: "068-p4", name: "Rodoviária", lineId: "068", order: 4, region: "Rodoviária" },
    { id: "068-p5", name: "Hospital Meridional", lineId: "068", order: 5, region: "Hospital Meridional" },
    { id: "068-p6", name: "Roberto Silvares", lineId: "068", order: 6, region: "Roberto Silvares" },
    { id: "068-p7", name: "FVC", lineId: "068", order: 7, region: "FVC" },
    { id: "068-p8", name: "CEPE", lineId: "068", order: 8, region: "CEPE" },
    { id: "068-p9", name: "Multivix", lineId: "068", order: 9, region: "Multivix" },
    { id: "068-p10", name: "San Remo", lineId: "068", order: 10, region: "San Remo" },
    { id: "068-p11", name: "Pedra D'Água", lineId: "068", order: 11, region: "Pedra D'Água" },
    { id: "068-p12", name: "Rio Preto", lineId: "068", order: 12, region: "Rio Preto" },
    { id: "068-p13", name: "Mariricu", lineId: "068", order: 13, region: "Mariricu" },
    { id: "068-p14", name: "Cascata", lineId: "068", order: 14, region: "Cascata" },
    { id: "068-p15", name: "Guriri", lineId: "068", order: 15, region: "Guriri" },
    { id: "068-p16", name: "Arena ao Mar", lineId: "068", order: 16, region: "Arena ao Mar" },
    { id: "068-p17", name: "Maria Amélia", lineId: "068", order: 17, region: "Maria Amélia" },
    { id: "068-p18", name: "IFES/UFES", lineId: "068", order: 18, region: "IFES" },
    { id: "068-p19", name: "US3", lineId: "068", order: 19, region: "US3" },
    { id: "068-p20", name: "Av. José Tozzi", lineId: "068", order: 20, region: "Av. José Tozzi" },
    { id: "068-p21", name: "BR-101", lineId: "068", order: 21, region: "BR-101" },
  ],
  "070": [
    { id: "070-p1", name: "Centro", lineId: "070", order: 1, region: "Centro" },
    { id: "070-p2", name: "CEPE", lineId: "070", order: 2, region: "CEPE" },
    { id: "070-p3", name: "Multivix", lineId: "070", order: 3, region: "Multivix" },
    { id: "070-p4", name: "Pedra D'Água", lineId: "070", order: 4, region: "Pedra D'Água" },
    { id: "070-p5", name: "Guriri", lineId: "070", order: 5, region: "Guriri" },
  ],
  "081": [
    { id: "081-p1", name: "Centro", lineId: "081", order: 1, region: "Centro" },
    { id: "081-p2", name: "Rodoviária", lineId: "081", order: 2, region: "Rodoviária" },
    { id: "081-p3", name: "Paulista", lineId: "081", order: 3, region: "Paulista" },
  ],
  "103": [
    { id: "103-p1", name: "Nova Era", lineId: "103", order: 1, region: "Nova Era" },
    { id: "103-p2", name: "Escola Master", lineId: "103", order: 2, region: "Escola Master" },
  ],
  "105": [
    { id: "105-p1", name: "Aroeira", lineId: "105", order: 1, region: "Aroeira" },
    { id: "105-p2", name: "Escola Master", lineId: "105", order: 2, region: "Escola Master" },
  ],
};

export function getPointsByLineId(lineId: string): PointData[] {
  return LINE_POINTS[lineId] || [];
}
